### ISSUE TITLE
There are always gpu out of memory errors in the anchor-matcher section

### ISSUE THREAD

**Issue by sunshuofeng** [facebookresearch/detectron2#1241]
The out of memory error always appear in the matcher section during training:

```
Traceback (most recent call last):
  File "main.py", line 68, in <module>
    loss_dict = model(data)
  File "/root/anaconda3/envs/python367/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/detectron2/detectron2/modeling/meta_arch/rcnn.py", line 124, in forward
    proposals, proposal_losses = self.proposal_generator(images, features, gt_instances)
  File "/root/anaconda3/envs/python367/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/detectron2/detectron2/modeling/proposal_generator/rrpn.py", line 53, in forward
    losses = outputs.losses()
  File "/root/detectron2/detectron2/modeling/proposal_generator/rpn_outputs.py", line 333, in losses
    gt_objectness_logits, gt_anchor_deltas = self._get_ground_truth()
  File "/root/detectron2/detectron2/modeling/proposal_generator/rrpn_outputs.py", line 223, in _get_ground_truth
    matched_idxs, gt_objectness_logits_i = self.anchor_matcher(match_quality_matrix)
  File "/root/detectron2/detectron2/modeling/matcher.py", line 98, in __call__
    self.set_low_quality_matches_(match_labels, match_quality_matrix)
  File "/root/detectron2/detectron2/modeling/matcher.py", line 118, in set_low_quality_matches_
    match_quality_matrix == highest_quality_foreach_gt[:, None], as_tuple=True

RuntimeError: CUDA out of memory. Tried to allocate 6.26 GiB (GPU 0; 10.76 GiB total capacity; 3.09 GiB already allocated; 6.00 GiB free; 3.11 GiB reserved in total by PyTorch)

```

This is my config in training:
```
cfg.DATASETS.TRAIN=('yaogan_train',)
cfg.DATALOADER.NUM_WORKERS=1
cfg.SOLVER.IMS_PER_BATCH=1
cfg.SOLVER.MAX_ITER=5000
cfg.SOLVER.CHECKPOINT_PERIOD=500

cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.MODEL.WEIGHTS=model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.MODEL.PROPOSAL_GENERATOR.NAME='RRPN'
cfg.MODEL.ANCHOR_GENERATOR.NAME='RotatedAnchorGenerator'
cfg.MODEL.ANCHOR_GENERATOR.ANGLES=[(-90,-60,-30,0,30,60,90)]
cfg.MODEL.ANCHOR_GENERATOR.SIZE=[[8,16,32,64,128]]
cfg.MODEL.RPN.BBOX_REG_WEIGHTS=(1.0,1.0,1.0,1.0,1.0)
cfg.MODEL.ROI_HEADS.NAME='RROIHeads'
cfg.MODEL.ROI_HEADS.NUM_CLASS=len(Train_Class_Name)
cfg.MODEL.ROI_BOX_HEAD.POOLER_TYPE='ROIAlignRotated'
cfg.OUTPUT_DIR='/root/yaogan/result'
cfg.MODEL.ROI_BOX_HEAD.BBOX_REG_WEIGHTS=(10.0,10.0,5.0,5.0,5.0)
```

The length and width of each picture are about 1000, and the instances of each picture are between 5 and more than 100. 
My gpu is 2080ti with 11019MB  memory.

I want to know if this error is due to data or configuration or gpu memory.

**Comment by sunshuofeng** [comment]
After observing the source code I found a problem：
In rpn_outputs, retry_if_cuda_oom was used, 
 ```
 match_quality_matrix = retry_if_cuda_oom(pairwise_iou)(gt_boxes_i, anchors_i)
            matched_idxs, gt_objectness_logits_i = retry_if_cuda_oom(self.anchor_matcher)(
                match_quality_matrix
            )

```
but in rrpn_outputs, it did not seem to be used.
```
 match_quality_matrix = pairwise_iou_rotated(gt_boxes_i, anchors_i)
            matched_idxs, gt_objectness_logits_i = self.anchor_matcher(match_quality_matrix)
```
 Retry_if_cuda_oom was supposed to handle cuda out of memory eroor in my opinion. 

Why not in RRPN?

**Comment by ppwwyyxx** [comment]
> Why not in RRPN?

You're welcome to add it. However it will not solve the root cause which is that you use too many anchors.

**Comment by sunshuofeng** [comment]
Thanks for your answer!

**Comment by TheanMS** [comment]
Hi, Even I am facing the same issue while training with the lower input size of 500 x 500 and i am using tesla v100 gpu . Any updates on the solution ?
