### ISSUE TITLE
RandomFlip does not flip the bounding boxes 

### ISSUE THREAD

**Issue by aviasd** [facebookresearch/detectron2#1854]
#1433  Instructions To Reproduce the Issue:
When using the [DefualtTrainer](https://github.com/facebookresearch/detectron2/blob/master/detectron2/engine/defaults.py#LC221), the trainer is doing some augmentations with the [DatasetMapper](url):  
```
[08/02 12:22:20 d2.data.dataset_mapper]: Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
```
When printing the images from the dataloader:
```
def show_images(images, rows, cols, titles=[]):
    y, x = images[0].shape[:2]
    if y < x:
        shape_factor = (4, 8)
    else:
        shape_factor = (8, 8)
    plt.figure(figsize=[cols*shape_factor[1], rows*shape_factor[0]])
    for i in range(len(images)):
            image = images[i]
            plt.subplot(rows, cols, i+1)
            if len(titles) > 0:
                plt.title(titles[i], fontsize=40)
            plt.axis("off")
            if len(image) == 3:
                plt.imshow(image)
            else:
                plt.imshow(image, cmap=plt.cm.gray)
    plt.show()

def create_dataset_image_from_dataloader_image(dataloader_image):
    dataloader_image
    dataset_image = {}
    dataset_image["file_name"] = dataloader_image['file_name']
    dataset_image["image_id"] = dataloader_image['image_id']
    dataset_image["height"] = dataloader_image['height']
    dataset_image["width"] = dataloader_image['width']
    
    instances = dataloader_image['instances'].to('cpu')
    boxes = instances.get_fields()['gt_boxes'].tensor.numpy().astype(int)

    objs = []
    for x1, y1, x2, y2 in boxes:

        obj = {
            'bbox': [x1, y1, x2, y2],
            'bbox_mode': BoxMode.XYXY_ABS,
            "category_id": 0,
        }
        objs.append(obj)

    dataset_image["annotations"] = objs
    return dataset_image
```
```
cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ('wheat_train',)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 1
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url('COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml')
cfg.SOLVER.IMS_PER_BATCH = 1
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.MAX_ITER = 10000 
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128 
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1


image_list = []
title_list = []
for i, b in enumerate(DefaultTrainer.build_train_loader(cfg )):
    d = create_dataset_image_from_dataloader_image(b[0])
    title_list.append(d["file_name"].split('/')[-1])

    image = cv2.imread(d["file_name"])
    visualizer = Visualizer(image, metadata=wheat_metadata_train, scale=0.5)
    out = visualizer.draw_dataset_dict(d)
    out_image = out.get_image()
    out_image = cv2.cvtColor(out_image, cv2.COLOR_BGR2RGB)
    image_list.append(out_image)
    if i >= 5:
        break
show_images(image_list, 2, 3, title_list)
```
The images are rotated but the bounding boxes are not:  

![image](https://user-images.githubusercontent.com/41818563/89122977-8bb0da80-d4d4-11ea-8ee9-e571477a0831.png)

## Expected behavior:

It should transform the bounding boxes too.  
Maybe it does this internally in the model somehow?  
If so, why not do it in the data loader?
By the way,   
I checked if the augmentations from fvcore are changing the bounding box. They are..  
It means that it is trying to change it in the dataloader, and it is not doing it for some reason.  

## Environment:

Provide your environment information using the following command:
```
/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py:125: UserWarning: 
Tesla T4 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the Tesla T4 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
----------------------  ---------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy                   1.18.5
detectron2              0.2 @/usr/local/lib/python3.6/dist-packages/detectron2
Compiler                GCC 7.5
CUDA compiler           CUDA 10.1
detectron2 arch flags   sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0+cu101 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   Tesla T4
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.7.0+cu101 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200716
cv2                     4.1.2
----------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by aviasd** [comment]
The problem was that I used `visualizer.draw_dataset_dict(d)` and it loaded the original image from the path while showing the augmented bboxes.
