### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by rohitashwa1907** [facebookresearch/detectron2#2006]
## Instructions To Reproduce the Issue:

1. I am using Chess-Pieces-Dataset with annotations in coco format. So I used the following command to register the dataset
```
register_coco_instances("chess_piece_train", {}, "/content/train_annotations.coco.json", "/content/chess_pieces/train")
```
2. Metadata for this dataset:
````
Metadata(evaluator_type='coco', image_root='/content/train_annotations.coco.json', name='chess_piece_train', thing_classes=['pieces', 'black-bishop', 'black-king', 'black-knight', 'black-pawn', 'black-queen', 'black-rook', 'white-bishop', 'white-king', 'white-knight', 'white-pawn', 'white-queen', 'white-rook'], thing_dataset_id_to_contiguous_id={0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12})

````
3. When i try to run the following block, as in the balloon tutorial, I get CUDA error: device-side assert triggered :
````
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg
import os

cfg = get_cfg()
cfg.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"))
cfg.DATASETS.TRAIN = ("chess_piece_train",)
cfg.DATASETS.TEST = ()  #"chess_piece_test",
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")  # Let training initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
cfg.SOLVER.MAX_ITER = 300    # 300 iterations seems good enough for this dataset
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 13  # number of classes (ballon)

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
````
4. Full Error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-59b40f59d6e9> in <module>()
     16 
     17 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
---> 18 trainer = DefaultTrainer(cfg)
     19 trainer.resume_or_load(resume=False)
     20 trainer.train()

7 frames
/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in __init__(self, cfg)
    271         cfg = DefaultTrainer.auto_scale_workers(cfg, comm.get_world_size())
    272         # Assume these objects must be constructed in this order.
--> 273         model = self.build_model(cfg)
    274         optimizer = self.build_optimizer(cfg, model)
    275         data_loader = self.build_train_loader(cfg)

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in build_model(cls, cfg)
    414         Overwrite it if you'd like a different model.
    415         """
--> 416         model = build_model(cfg)
    417         logger = logging.getLogger(__name__)
    418         logger.info("Model:\n{}".format(model))

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/build.py in build_model(cfg)
     20     meta_arch = cfg.MODEL.META_ARCHITECTURE
     21     model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
---> 22     model.to(torch.device(cfg.MODEL.DEVICE))
     23     return model

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in to(self, *args, **kwargs)
    605             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    606 
--> 607         return self._apply(convert)
    608 
    609     def register_backward_hook(

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    352     def _apply(self, fn):
    353         for module in self.children():
--> 354             module._apply(fn)
    355 
    356         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    352     def _apply(self, fn):
    353         for module in self.children():
--> 354             module._apply(fn)
    355 
    356         def compute_should_use_set_data(tensor, tensor_applied):

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
    374                 # `with torch.no_grad():`
    375                 with torch.no_grad():
--> 376                     param_applied = fn(param)
    377                 should_use_set_data = compute_should_use_set_data(param, param_applied)
    378                 if should_use_set_data:

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
    603             if convert_to_format is not None and t.dim() == 4:
    604                 return t.to(device, dtype if t.is_floating_point() else None, non_blocking, memory_format=convert_to_format)
--> 605             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
    606 
    607         return self._apply(convert)

RuntimeError: CUDA error: device-side assert triggered
```

## Expected behavior:
I am unable to train faster_rcnn_R_50_FPN model on my dataset.

## Environment:

Provide your environment information using the following command:
```
----------------------  ---------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
numpy                   1.18.5
detectron2              0.2.1 @/usr/local/lib/python3.6/dist-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   sm_35, sm_37, sm_50, sm_52, sm_60, sm_61, sm_70, sm_75
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.6.0+cu101 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     False
GPU available           True
GPU 0                   Tesla P100-PCIE-16GB
CUDA_HOME               /usr/local/cuda
Pillow                  7.2.0
torchvision             0.7.0+cu101 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  sm_35, sm_50, sm_60, sm_70, sm_75
fvcore                  0.1.1.post20200716
cv2                     4.1.2
----------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

Thanks for any suggestions.

**Comment by Shubhamai** [comment]
Yeah @rohitashwa1907 , I also got exact when i newly installed detectron2 today. But it simply solved by restarting the jupyter notebook.

**Comment by ppwwyyxx** [comment]
It looks like the GPUs in your environment are not functioning, which means the following code probably also fails; 
```python
import torch
for k in range(torch.cuda.device_count()):
    x = torch.tensor([1, 2.0], dtype=torch.float32)
    x = x.to(f"cuda:{k}")
```

**Comment by rohitashwa1907** [comment]
Thanks for all the suggestions.  Using a different colab instance solved the problem for me. So it must be an issue with that instance.

Closing the issue.
