### ISSUE TITLE
Training stuck if two nodes are set different number of gpus in distributed training.

### ISSUE THREAD

**Issue by kang235** [facebookresearch/detectron2#2128]
## Instructions To Reproduce the Issue:
1. full code you wrote or full changes you made (`git diff`)
n/a
2. what exact command you run:
_192.168.2.2:_
export GLOO_SOCKET_IFNAME=enp218s0f1 && NCCL_SOCKET_IFNAME=enp218s0f1 && export MASTER_ADDR=192.168.2.2 && export MASTER_PORT=3002 && ./tools/train_net.py  --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --num-gpus 2 --machine-rank 0 --num-machines 2 --dist-url tcp://192.168.2.2:3002
_192.168.2.1:_
export GLOO_SOCKET_IFNAME=enp218s0f1 && NCCL_SOCKET_IFNAME=enp218s0f1 && export MASTER_ADDR=192.168.2.2 && export MASTER_PORT=3002 && ./tools/train_net.py  --config-file configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml --num-gpus 1 --machine-rank 1 --num-machines 2 --dist-url tcp://192.168.2.2:3002
3. __full logs__ you observed:
_192.168.2.2:_
Failed to load OpenCL runtime
Command Line Args: Namespace(config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml', dist_url='tcp://192.168.2.2:3002', eval_only=False, machine_rank=0, num_gpus=2, num_machines=2, opts=['SOLVER.IMS_PER_BATCH', '2', 'SOLVER.BASE_LR', '0.0025', 'DATALOADER.NUM_WORKERS', '1', 'MODEL.ROI_HEADS.NUM_CLASSES', '7', 'DATASETS.TRAIN', '("mycoco_train",)', 'DATASETS.TEST', '("mycoco_train",)'], resume=False)
Failed to load OpenCL runtime
Failed to load OpenCL runtime

## Expected behavior:
The training should start.
**The training stuck if node0 and node1 are set to different number of gpus, e.g. 1 and 2. The training can start normally if node0 and node1 are set to the same number of gpus, e.g. 3 and 3.**

## Environment:

Docker provided in this repo.

**Comment by ppwwyyxx** [comment]
This setup is not supported because the command line arguments are not sufficient to tell how many workers are there in total.

However you can workaround it by launching one process at a time, pretending that each process is a new machine with 1 GPU, e.g.:
```
$(host0) CUDA_VISIBLE_DEVICES=0 train_net.py --num-gpus 1 --machine-rank 0 --num-machines 3
$(host0) CUDA_VISIBLE_DEVICES=1 train_net.py --num-gpus 1 --machine-rank 1 --num-machines 3
$(host1) CUDA_VISIBLE_DEVICES=0 train_net.py --num-gpus 1 --machine-rank 2 --num-machines 3
```

**Comment by kang235** [comment]
> This setup is not supported because the command line arguments are not sufficient to tell how many workers are there in total.
> 
> However you can workaround it by launching one process at a time, pretending that each process is a new machine with 1 GPU, e.g.:
> 
> ```
> $(host0) CUDA_VISIBLE_DEVICES=0 train_net.py --num-gpus 1 --machine-rank 0 --num-machines 3
> $(host0) CUDA_VISIBLE_DEVICES=1 train_net.py --num-gpus 1 --machine-rank 1 --num-machines 3
> $(host1) CUDA_VISIBLE_DEVICES=0 train_net.py --num-gpus 1 --machine-rank 2 --num-machines 3
> ```
> 
> You can also implement a variant of the `launch()` function https://detectron2.readthedocs.io/modules/engine.html#detectron2.engine.launch that supports such cluster configurations.

Thanks for the quick response. The workaround works like a charm. Does (1:1:1) theoretically give the same training efficiency as (2:1) (if implemented)?

**Comment by ppwwyyxx** [comment]
The speed should be the same in theory.

**Comment by kang235** [comment]
Thanks!
