### ISSUE TITLE
"RuntimeError: CUDA error: invalid device function (ROIAlign_forward_cuda at /home/oot/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign_cuda.cu:361)"how to solve?

### ISSUE THREAD

**Issue by Hondlus** [facebookresearch/detectron2#241]
I modified the tridentnet_fast_R_50_C4_1x.yaml file.I changed BATCH_SIZE_PER_IMAGE to 32,I changed IMS_PER_BATCH to 4.Then run this command "python /home/oot/detectron2/projects/TridentNet/train_net.py --config-file /home/oot/detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml".This is the result of the run.

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by Hondlus** [comment]
I modified the tridentnet_fast_R_50_C4_1x.yaml file.I changed BATCH_SIZE_PER_IMAGE to 32,I changed IMS_PER_BATCH to 4.Then run this command "python /home/oot/detectron2/projects/TridentNet/train_net.py --config-file /home/oot/detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml".This is the result of the run.

**Comment by ppwwyyxx** [comment]
Please include details about the problem following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by ntoxeg** [comment]
When I got such an error it was due to NVCC being for a different CUDA version than the one I actually use. In such case you need to ensure that you have the one that is needed in your `PATH` and rebuild detectron2.

**Comment by ZYN-guy** [comment]
> When I got such an error it was due to NVCC being for a different CUDA version than the one I actually use. In such case you need to ensure that you have the one that is needed in your `PATH` and rebuild detectron2.

Thanks,  My nvcc is 10.0, but my cuda is 10.1. What I want to say is that I have run other code before, no error is reported.

**Comment by ZYN-guy** [comment]
> When I got such an error it was due to NVCC being for a different CUDA version than the one I actually use. In such case you need to ensure that you have the one that is needed in your `PATH` and rebuild detectron2.



> I modified the tridentnet_fast_R_50_C4_1x.yaml file.I changed BATCH_SIZE_PER_IMAGE to 32,I changed IMS_PER_BATCH to 4.Then run this command "python /home/oot/detectron2/projects/TridentNet/train_net.py --config-file /home/oot/detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml".This is the result of the run.

I have the same problem. Have you solved it?

**Comment by lkmy** [comment]
> > When I got such an error it was due to NVCC being for a different CUDA version than the one I actually use. In such case you need to ensure that you have the one that is needed in your `PATH` and rebuild detectron2.
> 
> Thanks, My nvcc is 10.0, but my cuda is 10.1. What I want to say is that I have run other code before, no error is reported.

I used anaconda to build the envs and solved this by rebuild pytorch used cuda10.0 
【 conda install pytorch torchvision cudatoolkit=10.0 -c pytorch
    rm -rf build
   python setup.py build develop
  python -m detectron2.utils.collect_env
】  then it shows
[------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.3 |Anaconda, Inc.| (default, Nov  3 2017, 19:19:16) [GCC 7.2.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 7.1
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0,1,2,3               TITAN Xp
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.0.0
cv2                       4.1.1
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
]
you can see the Detectron2 CUDA Compiler and CUDA Runtime  is match as 10.0

**Comment by ppwwyyxx** [comment]
Closing as the requested information in the issue template was not provided.
