### ISSUE TITLE
How to run detectron2 with CUDA 11.1

### ISSUE THREAD

**Issue by HeliosZhao** [facebookresearch/detectron2#2557]
I worked with Pytorch 1.7 and CUDA 11.1.

Actually, I successfully build the detectron2 CUDA 11.0 version (No CUDA 11.1 version is available right?)

But I have trouble running the code

```
from detectron2 import _C
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

```

So how can I use detectron2 with CUDA 11.1?

**Comment by Data-drone** [comment]
I followed the steps to compile from source and it works fine on CUDA 11.1

**Comment by HeliosZhao** [comment]
Yeah, thanks for your answer.
Actually, I use the wrong version of detectron2. Now it works and I will close this issue.
