### ISSUE TITLE
Retrain for Panoptic segmentation with Mapillary fails at assertion

### ISSUE THREAD

**Issue by isagastiberri** [facebookresearch/detectron2#306]
## How To Reproduce the Issue

1. what changes you made (`git diff`) or what code you wrote
I wrote my own code to retrain the network for panoptic segmentation as expleined in #295 but I now use sem_seg_file_name as suggested by @ppwwyyxx 
2. what exact command you run
python train_panoptic.py
3. what you observed (including the full logs):
```
[11/12 15:30:07 d2.engine.train_loop]: Starting training from iteration 0
/opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:104: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [1,0,0], thread: [768,0,0] Assertion `t >= 0 && t < n_classes` failed.
```
This error appears about 50 times with different thread numbers. After this message I also get

``` 
[11/12 15:30:08 d2.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)
Traceback (most recent call last):
  File "tools/train_panoptic.py", line 37, in <module>
    trainer.train()
  File "/workspace/detectron2/detectron2/engine/defaults.py", line 350, in train
    super().train(self.start_iter, self.max_iter)
  File "/workspace/detectron2/detectron2/engine/train_loop.py", line 132, in train
    self.run_step()
  File "/workspace/detectron2/detectron2/engine/train_loop.py", line 212, in run_step
    loss_dict = self.model(data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 92, in forward
    gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
  File "/workspace/detectron2/detectron2/modeling/meta_arch/panoptic_fpn.py", line 92, in <listcomp>
    gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
  File "/workspace/detectron2/detectron2/structures/instances.py", line 111, in to
    v = v.to(device)
  File "/workspace/detectron2/detectron2/structures/boxes.py", line 108, in to
    return Boxes(self.tensor.to(device))
RuntimeError: CUDA error: device-side assert triggered
```

## Expected behavior

I wasn't expecting the code to break in the Assertion `t >= 0 && t < n_classes`. According to the [docs](https://detectron2.readthedocs.io/tutorials/datasets.html), a t=n_classes should be possible as it represents background category. I'm using the DefaultTrainer at detectron2 engine, should I modify anything from that class to train for panoptic?

## Environment

Please paste the output of `python -m detectron2.utils.collect_env`.

```
------------------------  -------------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 19:07:31) [GCC 7.3.0]
Numpy                     1.17.3
Detectron2 Compiler       GCC 5.4
Detectron2 CUDA Compiler  10.1
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     Quadro M6000
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.1, V10.1.243
Pillow                    6.2.1
cv2                       3.4.2
------------------------  -------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
 ```

**Comment by ppwwyyxx** [comment]
It seems your label files contain class indices that are larger than what's set in your config.

**Comment by EEEGUI** [comment]
@ppwwyyxx When I set `cfg.MODEL.ROI_HEADS.NUM_CLASSES = 1000`, this error will still appear.

**Comment by ppwwyyxx** [comment]
there is also `MODEL.SEM_SEG_HEAD.NUM_CLASSES`.

**Comment by isagastiberri** [comment]
@ppwwyyxx thanks! that solved it for me
