### ISSUE TITLE
Using Augmentation consumeing lot of GPU memory and the memory continously increasing !!

### ISSUE THREAD

**Issue by PushpakBhoge512** [facebookresearch/detectron2#3592]
If I use augumentation memory consumption goes through the roof
for every 500 iteration memory consumption increased by 2 GB  eventually leading to CUDA out of memory issue 
I have set the batch size to on initially it was around 3k then after some time 4k, 6k, 8k, 12k n out of memory

This is my trainer class
```
class CustomTrainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg_):
        return build_detection_train_loader(cfg_, mapper=DatasetMapper(cfg, is_train=True, augmentations=[
                                                        T.RandomBrightness(0.8, 1.8),
                                                        T.RandomContrast(0.6, 1.3),
                                                        T.RandomSaturation(0.8, 1.4),
                                                        T.RandomLighting(0.7),
                                                        T.RandomFlip(prob=0.5, horizontal=True, vertical=False),
                                                   ]))
```

If I did not use any augmentation then the memory do not increase its stays the same as the initial memory 
Please help is there anything wrong with the code ?

**Comment by gfiameni** [comment]
Having the same problem, even with one single transformation.

**Comment by gfiameni** [comment]
@PushpakBhoge512 I tried the following code and it works

```
from detectron2.data import detection_utils as utils
import detectron2.data.transforms as T
import copy

def custom_mapper(dataset_dict):
    dataset_dict = copy.deepcopy(dataset_dict)  # it will be modified by code below
    image = utils.read_image(dataset_dict["file_name"], format="BGR")
    transform_list = [
        T.Resize((800,600)),
        T.RandomBrightness(0.8, 1.8),
        T.RandomContrast(0.6, 1.3),
        T.RandomSaturation(0.8, 1.4),
        T.RandomRotation(angle=[90, 90]),
        T.RandomLighting(0.7),
        T.RandomFlip(prob=0.4, horizontal=False, vertical=True),
    ]
    image, transforms = T.apply_transform_gens(transform_list, image)
    dataset_dict["image"] = torch.as_tensor(image.transpose(2, 0, 1).astype("float32"))

    annos = [
        utils.transform_instance_annotations(obj, transforms, image.shape[:2])
        for obj in dataset_dict.pop("annotations")
        if obj.get("iscrowd", 0) == 0
    ]
    instances = utils.annotations_to_instances(annos, image.shape[:2])
    dataset_dict["instances"] = utils.filter_empty_instances(instances)
    return dataset_dict

from detectron2.engine import DefaultTrainer
from detectron2.data import build_detection_test_loader, build_detection_train_loader

class CustomTrainer(DefaultTrainer):
    @classmethod
    def build_train_loader(cls, cfg):
        return build_detection_train_loader(cfg, mapper=custom_mapper)
```
