### ISSUE TITLE
CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by danielbispov** [facebookresearch/detectron2#534]
## Instructions To Reproduce the Issue

1. I have this metadada from the dataset that I modified and loaded using 
```
register_coco_instances("mis", {}, "./Set1/missouri_camera_traps_set1.json", "./")
```
It is in COCO camera traps dataset format, so I loaded that way. I got the following metadata class from "MetadataCatalog.get("mis")":

```
Metadata(evaluator_type='coco', image_root='./', json_file='./Set1/missouri_camera_traps_set1.json', name='mis', thing_classes=['empty', 'agouti', 'collared_peccary', 'paca', 'red_brocket_deer', 'white-nosed_coati', 'spiny_rat', 'ocelot', 'red_squirrel', 'common_opossum', 'bird_spec', 'great_tinamou', 'white_tailed_deer', 'mouflon', 'red_deer', 'roe_deer', 'wild_boar', 'red_fox', 'european_hare', 'wood_mouse', 'coiban_agouti'], thing_dataset_id_to_contiguous_id={0: 0, 1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 12: 12, 13: 13, 14: 14, 15: 15, 16: 16, 17: 17, 18: 18, 19: 19, 20: 20})
```

2. When i try to run the following block, as in the balloon tutorial, I get the output written in the title of this post:

```
from detectron2.engine import DefaultTrainer
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_file("./detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
cfg.DATASETS.TRAIN = ("mis",)
cfg.DATASETS.TEST = ()
cfg.DATALOADER.NUM_WORKERS = 2
cfg.MODEL.WEIGHTS = "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"  # initialize from model zoo
cfg.SOLVER.IMS_PER_BATCH = 2
cfg.SOLVER.BASE_LR = 0.00025
cfg.SOLVER.MAX_ITER = 100    # 300 iterations seems good enough, but you can certainly train longer
cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 64   # faster, and good enough for this toy dataset
cfg.MODEL.ROI_HEADS.NUM_CLASSES = 21

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
trainer = DefaultTrainer(cfg) 
trainer.resume_or_load(resume=False)
trainer.train()
```

3. The full error is like this:
```
WARNING [12/16 08:47:28 d2.config.compat]: Config './detectron2_repo/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-332-6eeee973ba83> in <module>()
     22 
     23 os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)
---> 24 trainer = DefaultTrainer(cfg)
     25 trainer.resume_or_load(resume=False)
     26 trainer.train()

3 frames
/content/detectron2_repo/detectron2/modeling/meta_arch/rcnn.py in __init__(self, cfg)
     40         assert len(cfg.MODEL.PIXEL_MEAN) == len(cfg.MODEL.PIXEL_STD)
     41         num_channels = len(cfg.MODEL.PIXEL_MEAN)
---> 42         pixel_mean = torch.Tensor(cfg.MODEL.PIXEL_MEAN).to(self.device).view(num_channels, 1, 1)
     43         pixel_std = torch.Tensor(cfg.MODEL.PIXEL_STD).to(self.device).view(num_channels, 1, 1)
     44         self.normalizer = lambda x: (x - pixel_mean) / pixel_std

RuntimeError: CUDA error: device-side assert triggered
```
4. I don't know why it won't train. I've seen that it might be an issue with the number of classes declared, but I've tried many numbers, like 19-21 in "cfg.MODEL.ROI_HEADS.NUM_CLASSES".

## Environment

I am running on Google Colab

```
------------------------  --------------------------------------------------
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Numpy                     1.17.4
Detectron2 Compiler       GCC 7.4
Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     Tesla K80
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.1
cv2                       4.1.2
------------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

```

Thank you for your time.

**Comment by ppwwyyxx** [comment]
Your detectron2 is built with cuda 10.0:
> Detectron2 CUDA Compiler  10.0
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.3.1
PyTorch Debug Build       False
torchvision               0.4.2
CUDA available            True
GPU 0                     Tesla K80
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130

But your pytorch is running with cuda 10.1:
>   - CUDA Runtime 10.1

You need to make them consistent.

**Comment by danielbispov** [comment]
Thank you for the clarification. Would you have any tip on how can I perform that change?

**Comment by minhduc0711** [comment]
Hi, I'm having this same problem on Colab when trained with custom dataset, though my CUDA is consistent.
```
------------------------  ---------------------------------------------------------------
sys.platform              linux
Python                    3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
numpy                     1.17.5
detectron2                0.1 @/content/detectron2_repo/detectron2
detectron2 compiler       GCC 7.4
detectron2 CUDA compiler  10.0
detectron2 arch flags     sm_75
DETECTRON2_ENV_MODULE     <not set>
PyTorch                   1.4.0+cu100 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build       False
CUDA available            True
GPU 0                     Tesla T4
CUDA_HOME                 /usr/local/cuda
NVCC                      Cuda compilation tools, release 10.0, V10.0.130
Pillow                    6.2.2
torchvision               0.5.0+cu100 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags    sm_35, sm_50, sm_60, sm_70, sm_75
cv2                       4.1.2
------------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
```

**Comment by minhduc0711** [comment]
Apparently I did something wrong with the data register process, as it works after I restarted Colab.

**Comment by wangg12** [comment]
For me, it was because the wrong NUM_CLASSES in my config for a new dataset.

**Comment by dhirajsuvarna** [comment]
In my case, i am getting this error after the training starts. 

However, if I use `detectron2==0.1.3`  with `torch=1.5`, I **do not get this error**

## Error:
```
[12/09 06:52:35 d2.data.build]: Removed 0 images with no usable annotations. 401 images left.
[12/09 06:52:35 d2.data.build]: Distribution of instances among all 3 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   hindi    | 1881         |  english   | 491          |   others   | 18           |
|            |              |            |              |            |              |
|   total    | 2390         |            |              |            |              |
[12/09 06:52:35 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[12/09 06:52:35 d2.data.build]: Using training sampler TrainingSampler
[12/09 06:52:35 d2.data.common]: Serializing 401 elements to byte tensors and concatenating them all ...
[12/09 06:52:35 d2.data.common]: Serialized dataset takes 0.16 MiB

model_final_280758.pkl: 167MB [00:02, 73.0MB/s]                           
Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (4, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (4,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (12, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (12,) in the model! You might want to double check if this is expected.

[12/09 06:52:43 d2.engine.train_loop]: Starting training from iteration 0

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py:217: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /pytorch/torch/csrc/utils/python_arg_parser.cpp:882.)
  num_fg = fg_inds.nonzero().numel()

[12/09 06:53:01 d2.utils.events]:  eta: 0:21:35  iter: 19  total_loss: 2.339  loss_cls: 1.171  loss_box_reg: 0.5274  loss_rpn_cls: 0.4812  loss_rpn_loc: 0.08424  time: 0.8934  data_time: 0.0489  lr: 0.00024976  max_mem: 4966M
[12/09 06:53:20 d2.utils.events]:  eta: 0:22:08  iter: 39  total_loss: 1.472  loss_cls: 0.5815  loss_box_reg: 0.7138  loss_rpn_cls: 0.06965  loss_rpn_loc: 0.04425  time: 0.9087  data_time: 0.0101  lr: 0.00049951  max_mem: 4966M
[12/09 06:53:38 d2.utils.events]:  eta: 0:21:46  iter: 59  total_loss: 1.264  loss_cls: 0.426  loss_box_reg: 0.6417  loss_rpn_cls: 0.03986  loss_rpn_loc: 0.05194  time: 0.9031  data_time: 0.0104  lr: 0.00074926  max_mem: 4966M
ERROR [12/09 06:53:56 d2.engine.train_loop]: Exception during training:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 134, in train
    self.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py", line 166, in forward
    _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 688, in forward
    losses = self._forward_box(features, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py", line 754, in _forward_box
    losses = self.box_predictor.losses(predictions, proposals)
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 483, in losses
    self.box_reg_loss_type,
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 334, in losses
    return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
  File "/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py", line 267, in box_reg_loss
    fg_inds = nonzero_tuple((self.gt_classes >= 0) & (self.gt_classes < bg_class_ind))[0]
  File "/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py", line 128, in nonzero_tuple
    return x.nonzero(as_tuple=True)
RuntimeError: CUDA error: device-side assert triggered
[12/09 06:53:56 d2.engine.hooks]: Overall training speed: 77 iterations in 0:01:10 (0.9150 s / it)
[12/09 06:53:56 d2.engine.hooks]: Total training time: 0:01:10 (0:00:00 on hooks)
[12/09 06:53:56 d2.utils.events]:  eta: 0:21:24  iter: 79  total_loss: 1.058  loss_cls: 0.3424  loss_box_reg: 0.6057  loss_rpn_cls: 0.03864  loss_rpn_loc: 0.04465  time: 0.9021  data_time: 0.0097  lr: 0.00098653  max_mem: 4966M

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-11-159e26e6ebc2> in <module>()
      1 trainer = DefaultTrainer(cfg)
      2 trainer.resume_or_load(resume=False)
----> 3 trainer.train()

12 frames

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in train(self)
    411             OrderedDict of results, if evaluation is enabled. Otherwise None.
    412         """
--> 413         super().train(self.start_iter, self.max_iter)
    414         if len(self.cfg.TEST.EXPECTED_RESULTS) and comm.is_main_process():
    415             assert hasattr(

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in train(self, start_iter, max_iter)
    132                 for self.iter in range(start_iter, max_iter):
    133                     self.before_step()
--> 134                     self.run_step()
    135                     self.after_step()
    136                 # self.iter == max_iter can be used by `after_train` to

/usr/local/lib/python3.6/dist-packages/detectron2/engine/defaults.py in run_step(self)
    421     def run_step(self):
    422         self._trainer.iter = self.iter
--> 423         self._trainer.run_step()
    424 
    425     @classmethod

/usr/local/lib/python3.6/dist-packages/detectron2/engine/train_loop.py in run_step(self)
    226         If you want to do something with the losses, you can wrap the model.
    227         """
--> 228         loss_dict = self.model(data)
    229         losses = sum(loss_dict.values())
    230 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/meta_arch/rcnn.py in forward(self, batched_inputs)
    164             proposal_losses = {}
    165 
--> 166         _, detector_losses = self.roi_heads(images, features, proposals, gt_instances)
    167         if self.vis_period > 0:
    168             storage = get_event_storage()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in forward(***failed resolving arguments***)
    686         if self.training:
    687             assert not torch.jit.is_scripting()
--> 688             losses = self._forward_box(features, proposals)
    689             # Usually the original proposals used by the box head are used by the mask, keypoint
    690             # heads. But when `self.train_on_pred_boxes is True`, proposals will contain boxes

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/roi_heads.py in _forward_box(self, features, proposals)
    752         if self.training:
    753             assert not torch.jit.is_scripting()
--> 754             losses = self.box_predictor.losses(predictions, proposals)
    755             # proposals is modified in-place below, so losses must be computed first.
    756             if self.train_on_pred_boxes:

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self, predictions, proposals)
    481             proposals,
    482             self.smooth_l1_beta,
--> 483             self.box_reg_loss_type,
    484         ).losses()
    485         return {k: v * self.loss_weight.get(k, 1.0) for k, v in losses.items()}

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in losses(self)
    332             A dict of losses (scalar tensors) containing keys "loss_cls" and "loss_box_reg".
    333         """
--> 334         return {"loss_cls": self.softmax_cross_entropy_loss(), "loss_box_reg": self.box_reg_loss()}
    335 
    336     def predict_boxes(self):

/usr/local/lib/python3.6/dist-packages/detectron2/modeling/roi_heads/fast_rcnn.py in box_reg_loss(self)
    265         # arg to smooth_l1_loss is False (otherwise it uses torch.mean internally
    266         # and would produce a nan loss).
--> 267         fg_inds = nonzero_tuple((self.gt_classes >= 0) & (self.gt_classes < bg_class_ind))[0]
    268         if cls_agnostic_bbox_reg:
    269             # pred_proposal_deltas only corresponds to foreground class for agnostic

/usr/local/lib/python3.6/dist-packages/detectron2/layers/wrappers.py in nonzero_tuple(x)
    126         return x.nonzero().unbind(1)
    127     else:
--> 128         return x.nonzero(as_tuple=True)

RuntimeError: CUDA error: device-side assert triggered
```

## Environment:

```
----------------------  ---------------------------------------------------------------
sys.platform            linux
Python                  3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
numpy                   1.18.5
detectron2              0.3 @/usr/local/lib/python3.6/dist-packages/detectron2
Compiler                GCC 7.3
CUDA compiler           CUDA 10.1
detectron2 arch flags   3.7, 5.0, 5.2, 6.0, 6.1, 7.0, 7.5
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.7.0+cu101 @/usr/local/lib/python3.6/dist-packages/torch
PyTorch debug build     True
GPU available           True
GPU 0                   Tesla T4 (arch=7.5)
CUDA_HOME               /usr/local/cuda
Pillow                  8.0.1
torchvision             0.8.1+cu101 @/usr/local/lib/python3.6/dist-packages/torchvision
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5
fvcore                  0.1.2.post20201209
cv2                     4.1.2
----------------------  ---------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
```
Any help on this is greatly appreciated.

**Comment by markstrefford** [comment]
> Apparently I did something wrong with the data register process, as it works after I restarted Colab.

Restarting colab worked for me too.

**Comment by morganOliveira2018** [comment]
> Para mim, foi porque o NUM_CLASSES errado na minha configuração para um novo conjunto de dados.

@wangg12 Could you tell me how you discovered NUM_CLASSES, why is mine giving the same error? How did you fix it?

**Comment by wangg12** [comment]
@morganOliveira2018 Since for my dataset, the number of classes is not the same as coco, the error occurred.

**Comment by morganOliveira2018** [comment]
How did you identify the number of classes for this in code form? Would you
help me. Because I did my labeling on Labelme, some labels are repeated.

Em qua, 3 de mar de 2021 22:35, Gu Wang <notifications@github.com> escreveu:

**Comment by morganOliveira2018** [comment]
@wangg12 How did you identify the number of classes for this in code form? Would you
help me. Because I did my labeling on Labelme, some labels are repeated.

1. Here the code I applied to show the labels:
````
classes = MetadataCatalog.get("fishesSegmentation_train").thing_classes
print("Classes:", classes)
````

2. Output:
````
Classes: ['anal fin Atlantic  Mackerel', 'anal fin Atlantic Mackerel', 'anal fin Lane Snapper', 'anal fin Mutton Snapper', 'black spot Lane Snapper', 'black spot Mutton Snapper', 'body', 'body Atlantic Mackerel', 'body Lane Snapper', 'body Mutton Snapper', 'caudal Lane Snapper', 'caudal fin Atlantic Mackerel', 'caudal fin Lane Snapper', 'caudal fin Mutton Snapper', 'dorsal', 'dorsal fin Atlantic Mackerel', 'dorsal fin Lane Snapper', 'dorsal fin Mutton Snapper', 'eye', 'eye Atlantic Mackerel', 'eye Lane Snapper', 'eye Mutton Snapper', 'mouth', 'mouth Lane Snapper', 'mouth Mutton Snapper', 'pectoral Mutton Snapper', 'pectoral fin Atlantic Mackerel', 'pectoral fin Lane Snapper', 'pectoral fin Mutton Snapper', 'pelvic', 'pelvic fin Atlantic Mackerel', 'pelvic fin Lane Snapper', 'pelvic fin Mutton Snapper', 'snout', 'snout Atlantic Mackerel', 'snout Lane Snapper', 'snout Mutton Snapper', 'spines Atlantic Mackerel']
````

3. I applied a len() to count the labels placed on Labelme. I did it like this:
`print ("Classes:", len(classes))` - Output: 38

**Doubt: Do the repeated ones I count as being unique?**

4. I tested the snippet with: `cfg.MODEL.ROI_HEADS.NUM_CLASSES = 38`, 
but keep the error: `CUDA error: device-side assert triggered`!

**Comment by wangg12** [comment]
I think you might need to manually asign `thing_classes` for your custom registered dataset to avoid duplicated classes.

**Comment by morganOliveira2018** [comment]
@wangg12 How can I manually assign `thing_classes`, because you think you are reading from `train.json`, do I edit by hand only the labels I want in the train.json file or is there another way via code?

**Comment by wangg12** [comment]
You can directly modify the metadata for your dataset when you register the dataset following the document of custom dataset in detectron2.
