### ISSUE TITLE
Deadlock when multiple gpus are enabled

### ISSUE THREAD

**Issue by RafaelMostert** [facebookresearch/detectron2#840]
Calling the same script with multiple gpu's redirects the output to some place unknown to me.

## Instructions To Reproduce the Issue:

2. what exact command you run:
`CUDA_VISIBLE_DEVICES=2 python detectron2/projects/TridentNet/train_net.py --config-file detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml --num-gpus 1`
Works as expected.
While:
`CUDA_VISIBLE_DEVICES=2,3 python detectron2/projects/TridentNet/train_net.py --config-file detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml --num-gpus 2`
only produces the following output from command line arg parse.
`Command Line Args: Namespace(config_file='detectron2/projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml', dist_url='tcp://127.0.0.1:54528', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)`
3. what you observed (including the full logs):

Nvidia-smi shows, the gpu's are running at 100% capacity, but no output is generated inside the output directory. (Unlike the single gpu-case which works fine.) 

Where does the logger output go in this case?
## Expected behavior:
I expect to see the logger info.

## Environment:
`
-----------------------------------------  -----------------------------------------------------------------------------------------
sys.platform                               linux
Python                                     3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) [GCC 7.3.0]
numpy                                      1.18.1
detectron2                                 0.1 @/data/mostertrij/tridentnet/detectron2/detectron2
detectron2 compiler                        GCC 7.3
detectron2 CUDA compiler                   10.1
detectron2 arch flags                      sm_37
DETECTRON2_ENV_MODULE                      <not set>
PyTorch                                    1.3.1 @/home/mostertrij/anaconda3/envs/tridentnet/lib/python3.7/site-packages/torch
PyTorch debug build                        False
CUDA available                             True
GPU 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15  Tesla K80
CUDA_HOME                                  /usr/local/cuda
NVCC                                       Cuda compilation tools, release 10.1, V10.1.168
Pillow                                     7.0.0
torchvision                                0.4.2 @/home/mostertrij/anaconda3/envs/tridentnet/lib/python3.7/site-packages/torchvision
torchvision arch flags                     sm_35, sm_50, sm_60, sm_70, sm_75
cv2                                        4.1.2
-----------------------------------------  -----------------------------------------------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.20.5 (Git Hash 0125f28c61c1f822fd48570b4c1066f96fcb9b2e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=True, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 
`

**Comment by ppwwyyxx** [comment]
If you need help with an unexpected issue, please include details following the [issue template](https://github.com/facebookresearch/detectron2/issues/new?template=unexpected-problems-bugs.md).

**Comment by RafaelMostert** [comment]
Updated the issue

**Comment by ppwwyyxx** [comment]
I can observe logs when running the same command.
Did you make any modifications to code?

**Comment by RafaelMostert** [comment]
No modifications.
I rebuilded a local version of detectron2 to make sure.

`Command Line Args: Namespace(config_file='projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml', dist_url='tcp://127.0.0.1:54528', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
`
is the only visible output produced when --num-gpus > 1
also no log.txt or config.yaml are produced in the output folder, while they do get produced for --num-gpus 1

**Comment by RafaelMostert** [comment]
Maybe the keyboardinterrupt traceback output, produced when
`CUDA_VISIBLE_DEVICES=2,3 python projects/TridentNet/train_net.py --config-file projects/TridentNet/configs/tridentnet_fast_R_50_C4_1x.yaml --num-gpus 2`
gets interrupted helps:


Traceback (most recent call last):
  File "projects/TridentNet/train_net.py", line 64, in <module>
    args=(args,),
  File "/data/mostertrij/scrap/detectron2/detectron2/engine/launch.py", line 49, in launch
    daemon=False,
  File "/home/mostertrij/anaconda3/envs/tridentclone/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/mostertrij/anaconda3/envs/tridentclone/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 77, in join
    timeout=timeout,
  File "/home/mostertrij/anaconda3/envs/tridentclone/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/mostertrij/anaconda3/envs/tridentclone/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by ppwwyyxx** [comment]
It's stuck in `torch.multiprocessing.spawn`, so it's either a problem of your environment or pytorch.
It may help to use a different port in `--dist-url`

**Comment by RafaelMostert** [comment]
Thanks. It is apparently a known pytorch deadlock issue: https://github.com/pytorch/pytorch/issues/32322

replacing:
https://github.com/facebookresearch/detectron2/blob/a809b8670d29693076f28eeb4a94838072ccd0d9/detectron2/engine/launch.py#L45-L50

with:
```
        for i in range(world_size):
            p = mp.Process(target=_distributed_worker,
                    args=(i, main_func, world_size,
                        num_gpus_per_machine, machine_rank,
                        dist_url, args))
            p.start()
```
solves my problem.

**Comment by jvlmdr** [comment]
I think I encountered the same issue. I was calling `train_net.py --eval-only` with `--num-gpus=4` and the program was often (but not always) encountering a deadlock at `comm.synchronize()`. I checked the log files and all 4 processes had reached this point. I am using commit 0130967d72346c520c9508620a6833fcef135cee, `torch==1.6.0+cu101` on Debian.

For me, this problem seems to have been fixed by calling `mp.set_start_method('spawn')` before `mp.spawn()` (the default start method was `'fork'`). The workaround above using `mp.Process()` did not help my situation.

**Comment by ppwwyyxx** [comment]
`mp.spawn` already uses spawn start method: https://pytorch.org/docs/stable/multiprocessing.html#torch.multiprocessing.spawn
So it would be strange if your solution helps. If you find out why you may report the issue to pytorch.

**Comment by jvlmdr** [comment]
Thanks for the fast response on a closed issue. Yeah, I see, the fix doesn't really make sense, also because the function `set_start_method()` is actually imported from the builtin `multiprocessing` (and is a bound method of the `multiprocessing.context.DefaultContext` object). I will try to investigate it further

**Comment by lydials** [comment]
I also encounter the same problem on a workstation. I change the backend from "NCCL" to "gloo" in this line and the problem is solved.
https://github.com/facebookresearch/detectron2/blob/7007c4e85be451aa2d60e05be8b5ea983cfaf8cf/detectron2/engine/launch.py#L72
I think it is related to the machine.

**Comment by ppwwyyxx** [comment]
Another possibility of NCCL getting suck is wrong NCCL configuration (often inside containers) https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#pci-access-control-services-acs
